name: Setup Rust Build Environment
description: Install Rust and cache Cargo dependencies

inputs:
  target:
    description: "Rust target triple (e.g., x86_64-unknown-linux-gnu)"
    required: true

runs:
  using: composite
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}

    - name: Verify Rust installation
      shell: bash
      run: |
        # Ensure cargo is in PATH
        export PATH="$HOME/.cargo/bin:$PATH"
        echo "PATH=$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

        # Verify installation
        if ! command -v cargo &> /dev/null; then
          echo "❌ Error: cargo not found after installation"
          echo "PATH: $PATH"
          echo "Checking ~/.cargo/bin..."
          ls -la ~/.cargo/bin/ 2>/dev/null || echo "~/.cargo/bin/ does not exist"
          exit 1
        fi

        echo "✓ Rust version: $(rustc --version)"
        echo "✓ Cargo version: $(cargo --version)"
        echo "✓ Cargo path: $(which cargo)"

    - name: Cache Cargo dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ runner.tool_cache }}/cargo
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ inputs.target }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.target }}-
          ${{ runner.os }}-cargo-
