#!/bin/bash

# Setup SSH hosts in ~/.ssh/config from .env file
# Reads SSH_<HOST>_HOST, SSH_<HOST>_USER, SSH_<HOST>_PORT from .env
# Example: SSH_MAPLE_HOST="10.10.10.130", SSH_MAPLE_USER="skey"

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

SSH_CONFIG="$HOME/.ssh/config"
SSH_CONFIG_BACKUP="${SSH_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"

# Find .env file
find_env_file() {
    local current="$(pwd)"
    while [ "$current" != "/" ]; do
        if [ -f "$current/.env" ]; then
            echo "$current/.env"
            return 0
        fi
        current="$(dirname "$current")"
    done
    return 1
}

ENV_FILE=$(find_env_file)

if [ -z "$ENV_FILE" ]; then
    echo -e "${RED}Error: .env file not found${NC}"
    echo "Please run this script from within your homelab directory or ensure .env exists"
    exit 1
fi

echo -e "${GREEN}Found .env file: ${ENV_FILE}${NC}"
echo "Setting up SSH hosts from .env configuration..."

# Source .env file
set -a
source "$ENV_FILE"
set +a

# Create .ssh directory if it doesn't exist
mkdir -p "$HOME/.ssh"
chmod 700 "$HOME/.ssh"

# Backup existing config if it exists
if [ -f "$SSH_CONFIG" ]; then
    echo -e "${YELLOW}Backing up existing SSH config to: ${SSH_CONFIG_BACKUP}${NC}"
    cp "$SSH_CONFIG" "$SSH_CONFIG_BACKUP"
fi

# Extract SSH host configurations from environment
declare -A ssh_hosts
declare -A ssh_users
declare -A ssh_ports

for var in $(compgen -v | grep "^SSH_.*_HOST$"); do
    # Extract hostname from SSH_<HOST>_HOST
    hostname=$(echo "$var" | sed 's/^SSH_\(.*\)_HOST$/\1/' | tr '[:upper:]' '[:lower:]')
    host_value="${!var}"
    
    if [ -n "$host_value" ]; then
        ssh_hosts["$hostname"]="$host_value"
        
        # Check for corresponding USER and PORT
        user_var="SSH_${hostname^^}_USER"
        port_var="SSH_${hostname^^}_PORT"
        
        if [ -n "${!user_var}" ]; then
            ssh_users["$hostname"]="${!user_var}"
        fi
        
        if [ -n "${!port_var}" ]; then
            ssh_ports["$hostname"]="${!port_var}"
        fi
    fi
done

if [ ${#ssh_hosts[@]} -eq 0 ]; then
    echo -e "${YELLOW}No SSH host configurations found in .env${NC}"
    echo "Add entries like:"
    echo "  SSH_MAPLE_HOST=\"10.10.10.130\""
    echo "  SSH_MAPLE_USER=\"skey\""
    echo "  SSH_MAPLE_PORT=\"22\""
    exit 0
fi

# Generate SSH config entries
{
    echo "# SSH hosts configured from .env file"
    echo "# Generated by setup-ssh-hosts.sh on $(date)"
    echo "#"
    
    for hostname in $(printf '%s\n' "${!ssh_hosts[@]}" | sort); do
        host_value="${ssh_hosts[$hostname]}"
        user_value="${ssh_users[$hostname]}"
        port_value="${ssh_ports[$hostname]}"
        
        echo ""
        echo "Host $hostname"
        echo "    HostName $host_value"
        
        if [ -n "$user_value" ]; then
            echo "    User $user_value"
        fi
        
        if [ -n "$port_value" ]; then
            echo "    Port $port_value"
        fi
        
        echo "    StrictHostKeyChecking no"
        echo "    PreferredAuthentications publickey"
        echo "    PasswordAuthentication no"
    done
} > "$SSH_CONFIG.tmp"

# Append to existing config if it exists and doesn't have our marker
if [ -f "$SSH_CONFIG" ] && ! grep -q "# SSH hosts configured from .env file" "$SSH_CONFIG"; then
    echo "" >> "$SSH_CONFIG"
    cat "$SSH_CONFIG.tmp" >> "$SSH_CONFIG"
    rm "$SSH_CONFIG.tmp"
else
    mv "$SSH_CONFIG.tmp" "$SSH_CONFIG"
fi

chmod 600 "$SSH_CONFIG"

echo -e "${GREEN}✓ SSH config updated${NC}"
echo ""
echo "Configured hosts:"
for hostname in $(printf '%s\n' "${!ssh_hosts[@]}" | sort); do
    host_value="${ssh_hosts[$hostname]}"
    user_value="${ssh_users[$hostname]:-default}"
    port_value="${ssh_ports[$hostname]:-22}"
    echo "  - $hostname -> ${user_value}@${host_value}:${port_value}"
done

echo ""
echo -e "${GREEN}You can now connect using: ssh $hostname${NC}"
